export const canciones = [
    {
        id: 1,
        nombre : "Grande y Fuerte",
        interprete: "Miel San Marcos",
        genero: "",
        categorias:"Alabanza,Jubilo",
        link: "https://www.youtube.com/watch?v=BrePZu_mJYc&ab_channel=Cantale",
    },
    {
        id: 2,
        nombre : "Amado de mi alma",
        interprete: "Alex Márquez",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=vDnvuUcfwjQ&ab_channel=CristianosMusicOficial",
    },
    {
        id: 3,
        nombre : "A donde huiré",
        interprete: "Kabed",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=l59n0CT6_-E&ab_channel=KabedOficial",
    },
    {
        id: 4,
        nombre : "Aceite Fresco",
        interprete: "New Wine",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=p_bY_SPtQQg&ab_channel=NewWine",
    },
    {
        id: 5,
        nombre : "Al estar aquí",
        interprete: "Danilo Montero",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=77pgHk5PSyk&ab_channel=MusicaCristiana-letras.",
    },
    {
        id: 6,
        nombre : "Al que está sentado en el trono",
        interprete: "Marcos Brunet Ft Lucas Conslie",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=P1sPgXvuKwI&ab_channel=CLAMORYFUEGO",
    },
    {
        id: 7,
        nombre : "Algo esta pasando",
        interprete: "Oasis Ministry",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=jw0oO0d63MQ&ab_channel=OASISMINISTRY",
    },
    {
        id: 8,
        nombre : "Ante tu Altar",
        interprete: "Averly Morillo",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=SaBGDaZXAjI&ab_channel=AverlyMorillo",
    },
    {
        id: 9,
        nombre : "Aquí estas (Way Maker)",
        interprete: "Priscilla Bueno",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=Dj8gGf7-FVI&ab_channel=MusicaCristianaGospel",
    },
    {
        id: 10,
        nombre : "Aquí estas (Way Maker)",
        interprete: "Su Presencia Worship",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=RJ-IMhpLZTY&ab_channel=SuPresenciaWorship",
    },
    {
        id: 11,
        nombre : "Que los cielos se abran aquí (Ángeles que suben)",
        interprete: "New Wine",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=7X2OrKgZT3s&ab_channel=JoshuaChavarria",
    },
    {
        id: 12,
        nombre : "Como dijiste",
        interprete: "Christine D’Clario",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=hMhzsC74Lgo&ab_channel=EladioAguilera",
    },
    {
        id: 13,
        nombre : "Creo En Ti",
        interprete: "Julio Melgar",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=KaNsqrxZo40&ab_channel=LivingWorship.",
    },
    {
        id: 14,
        nombre : "Cuan Grande Es Dios",
        interprete: "En Espíritu Y En Verdad",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=wHuQ-sIAFHM&ab_channel=A.T.",
    },
    {
        id: 15,
        nombre : "Das Vida",
        interprete: "World Worship ft Kairo Worship",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=D2y_aw8wWy4&ab_channel=Adoremos-M%C3%BAsicaCristianaconLetras",
    },
    {
        id: 16,
        nombre : "Derramo el Perfume",
        interprete: "Montesanto ft Averly Morillo",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=6IPuB7PMYR0&ab_channel=UngidosA120",
    },
    {
        id: 17,
        nombre : "Deseo Eterno/Yeshua",
        interprete: "Yvonne Muñoz",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=JAjCbz_PzvA&ab_channel=CasaDeLasNaciones",
    },
    {
        id: 18,
        nombre : "Día y Noche",
        interprete: "New Wine",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=qadovWH_Xn0&ab_channel=NewWine",
    },
    {
        id: 19,
        nombre : "Dios Incomparable",
        interprete: "Marco Barrientos",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=WmcSy89s9Ww&ab_channel=CMAMusic",
    },
    {
        id: 20,
        nombre : "El Shaddai",
        interprete: "Christine D’Clairo ft Gateway Worship",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=PGrnwNBFjgQ&ab_channel=GatewayWorshipEspa%C3%B1ol",
    },
    {
        id: 21,
        nombre : "En los brazos de Papa",
        interprete: "Grupo Grace ft Oasis Ministry",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=E0P4P0Z42j4&ab_channel=AnchorLyricsOficial",
    },
    {
        id: 22,
        nombre : "Espíritu Santo (Aviva En Mi Tu Fuego)",
        interprete: "Josué del Cid",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=6eJa1mMCOR8&ab_channel=Hugoes",
    },
    {
        id: 23,
        nombre : "Estar contigo",
        interprete: "Job González",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=Nd5cIiRCTmM&ab_channel=CONTODOLOQUESOY",
    },
    {
        id: 24,
        nombre : "Estar contigo",
        interprete: "Priscilla Bueno",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=wQIknkfefaQ&ab_channel=CaminandobajolaBendici%C3%B3ndeDios",
    },
    {
        id: 25,
        nombre : "Fidelidad (Grande Es Tu Fidelidad)",
        interprete: "Christine D'Clario ft Daniel Calveti",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=GoynWuL6Kqc&ab_channel=NeftaliLaboy",
    },
    {
        id: 26,
        nombre : "Gracias",
        interprete: "New Wine",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=1LAftQaZ5AM&ab_channel=Jos%C3%A9M",
    },
    {
        id: 27,
        nombre : "Hay momentos",
        interprete: "Danilo Montero",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=bSbFPlvGMdI&ab_channel=EladioAguilera",
    },
    {
        id: 28,
        nombre : "Haz Un Milagro En Mí (Como Zaqueo)",
        interprete: "Jonathan Giménez",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=Z_QdsHKluIs&ab_channel=JonathanGim%C3%A9nez-Topic",
    },
    {
        id: 29,
        nombre : "Hermoso Momento",
        interprete: "Kairo Worship",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=tSet0EXS8dA&ab_channel=MusicaCristianaConLetraOficial",
    },
    {
        id: 30,
        nombre : "Inexplicable",
        interprete: "Denicher Pol",
        genero: "",
        categorias:"Adoración",
        link: "https://www.youtube.com/watch?v=_XXGJqnv35c&ab_channel=LizethMartinez",
    },

] 
